<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <!-- Run on whatever newer runtime is installed -->
        <RollForward>Major</RollForward>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>9.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\SWCUOPlugin\NativeTrampoline.cs" Link="NativeTrampoline.cs" />
    </ItemGroup>
</Project>
